### ISSUE TITLE
Can't serialize my flux instance

### ISSUE THREAD

**Issue by fkrauthan** [acdlite/flummox#102]
I started using flummox today. But when I try to call `flux.serialize()` I just get a empty result back. I've debugged it and my flux instance contains a store with a state that contains an element.

I've looked a little bit within the serialize call of Flux and found out that the Store doesn't have a serialize function. It stops here: `if (typeof serialize !== 'function')`.

Any idea why? My store follows the basic example:

````javascript
import { Store } from 'flummox';

export default class NavigationStore extends Store {

  constructor(flux) {
      super();

      let navigationActionIds = flux.getActionIds('navigation');
      this.register(navigationActionIds.changePath, this.handleChangePath);

      this.state = {
          path: '/'
      };
  }

  handleChangePath({ newPath }) {
      this.setState({
          path: newPath
      });
  }

  getPath() {
      return this.state.path;
  }

}
````

Any ideas what I may miss? Right now I am using version `2.13.2`

**Comment by acdlite** [comment]
Serialization is opt-in, since you may have sensitive information in some of your stores (though you shouldn't) or you may be using data types that aren't JSON serializable.

To enable, define the static methods `serialize()` and `deserialize()` on your store's class as described here:

https://github.com/acdlite/flummox/blob/master/docs/api/Flux.md#serializationdeserialization

You'll likely want to share the same methods for multiple classes. You can use a base store class and extend from that, or use a mixin pattern.

Hope that helps!

**Comment by fkrauthan** [comment]
Maybe we could add some sort of SerializedStore instance that does exactly that within flummox? Would a PR regarding that accepted? I think often people want that and we could just run the state through JSON.stringify by default?

**Comment by acdlite** [comment]
Hmm, I can see the benefit of that. Rather than provide a SerializedStore class, though, I think it might be better to provide it as plugin/mixin. That way we don't encourage long inheritance chains (Store -> SerializedStore -> MyStore).

```js
function serializationPlugin(StoreClass) {
  StoreClass.serialize = function(state) {...}
  StoreClass.deserialize = function(state) {...}

  return StoreClass;
}

// in your app's store modules
class MyStore extends Store {...}
serializationPlugin(StoreClass);
```

I don't know if "serializationPlugin" is the right name for it, though.

**Comment by fkrauthan** [comment]
Yeah something like that. Or StateRestorePlugin since it is mainly used to save a state to restore it later on the client side.

**Comment by acdlite** [comment]
I'll reopen this in case anyone wants to submit a PR for a plugin/mixin/whatever we're calling it. At the very least we need better docs on serialization.

**Comment by fkrauthan** [comment]
Ok gonna submit a pull request soon for that.
