### ISSUE TITLE
Passing more information to storeStateGetter

### ISSUE THREAD

**Issue by mikeachen** [acdlite/flummox#152]
Apologies if this is the wrong forum for this kind of question.

I notice that `this.props` is passed to the storeStateGetter ([link](https://github.com/acdlite/flummox/blob/master/src/addons/reactComponentMethods.js#L187)).

Might it be useful to pass `this.context` as well? Can you help me understand why we might not want to pass `this.context` or even just `this`?

**Comment by acdlite** [comment]
`this.context` only works if you specifically declare `contextTypes`. For `FluxComponent` to support this would require enough complexity that it's not worth it. Instead, get the context in the parent container and pass it as a prop.

We used to bind the component instance to the state getter, but this caused problems when using `componentWillUpdate`, since `nextProps` is not the same as `this.props`. More background here: https://github.com/acdlite/flummox/pull/31#issuecomment-77697480
