### ISSUE TITLE
Can't return nothing from action

### ISSUE THREAD

**Issue by mikeachen** [acdlite/flummox#172]
Hey, thanks for your great work. I've been enjoying using Flummox immensely.

One thing I've noticed is that you can't just `return;` in an action. Due to [this conditional](https://github.com/acdlite/flummox/blob/master/src/Actions.js#L80), the action will never be dispatched. What's the reasoning behind this? Sometimes, the only relevant data for an action is the fact that it's been fired, and right now we have to `return null;`, which is a mild inconvenience.

Thanks!

**Comment by jordansexton** [comment]
+1 on this issue. I also found this to be unexpected and return null from my actions in a few places because of it.

**Comment by acdlite** [comment]
I agree this is somewhat surprising. The idea is that we need a way to cancel a dispatch from within an action. Returning `undefined` seemed like the most natural way to do this. Do you have an alternate suggestion?

**Comment by tappleby** [comment]
Perhaps we could have a special constant you could return `Actions.CANCEL`?

**Comment by bdowning** [comment]
For what it's worth, when I was looking into avoiding dispatching an action from a Flummox action creator returning `undefined` was my first guess (which happened to be right).  So it makes sense at least to me.

**Comment by acdlite** [comment]
Yeah I want to think about this some more. In a normal function (which is how I prefer to think of Flummox's actions — functions with transparent side effects), returning essentially always means "cancel" because otherwise, if it comes at the end, the statement is superfluous. So while I do see the potential for confusion, I think this is solvable with better documentation. As an alternative, I like the idea of returning a special constant to cancel, but I still prefer the current behavior.

**Comment by jordansexton** [comment]
How common of a use case is it to cancel actions? What would be wrong with something like `this.cancelAction()` rather than magical behavior based on a special return value?

**Comment by jtremback** [comment]
Returning `null` seems like a pretty reasonable thing to do. I mean, you use it when there is no value. Null.

**Comment by bdowning** [comment]
`undefined` makes a lot more sense to return than `null` to not dispatch.  For example, a `null` may be heading to a database as a SQL NULL.  (I know the concepts of a Javascript `null` and a SQL NULL are not the same, but many frameworks use one to represent the other.)

`undefined`, on the other hand, is rarely used outside of Javascript, or is used to represent the absense of something in an external representation, i.e. `{ absentKey: undefined }` will convert to JSON as `{ }`.

I think if anything this is just a documentation problem.  All Flummox actions (i.e. the things dispatched from action creators) must have a single value.  If the action creator does not provide this value, no action is dispatched.  This makes sense.  (Maybe it's a bit unfortunate that `Action`s are called actions and not action creators... granted the latter is quite a clumsy name but it is a better description of what's going on.)

**Comment by johanneslumpe** [comment]
I'm definitely for keeping this behavior. Because it allows us to write actions, which only act as wrapper actions to call other actions in sequence. Having to call a method to explicitly cancel the dispatch of an action seems a bit uncomfortable to me.

In addition `undefined` is preferable to `null` just because of the fact that not returning anything implicitly returns `undefined`.

@acdlite are we clear on this? Can this be closed?

**Comment by jordansexton** [comment]
Calling a method to cancel the dispatch of an action is no different than calling `event.preventDefault()`, `event.stopPropagation()`, `promise.cancel()`, etc. Being explicit about canceling an action with an API to do so seems much better than magical behavior based on a special return value.

**Comment by bdowning** [comment]
I definitely prefer the existing behavior.  However, `this.cancelAction()` would appear to be pretty hard to implement, since you need to know which action to cancel.  Since you can have async actions it's not necessarily going to be the one on the stack.  You could fabricate a new `this` for each action, but that sounds ugly and confusing (property assignments to `this` wouldn't be visible in other actions...).  You can't even do something like `this.cancelAction(this.actionName)` because you can have multiple `this.actionName`s outstanding at once if they're async.

**Comment by jordansexton** [comment]
I'm not sure I understand. `this.cancelAction()` can always be executed synchronously (if it executes async, the action must return a promise, thus not being cancelled). I don't see the source of ambiguity of the action being cancelled.

**Comment by jordansexton** [comment]
Sample implementation modified from [current behavior](https://github.com/acdlite/flummox/blob/master/src/Actions.js#L54-L81):

```javascript
  _wrapAction(methodName) {
    const originalMethod = this[methodName];
    const actionId = this._createActionId(methodName);

    const action = (...args) => {
      this.shouldDispatch = true;
      const body = originalMethod.apply(this, args);

      if (this.shouldDispatch) {
        const payload = {
          actionArgs: args
        };

        if (isPromise(body)) {
          const promise = body;
          this.dispatchAsync(actionId, promise, payload);
        } else {
          this.dispatch(actionId, body, payload);
        }
      }

      // Return original method's return value to caller
      return body;
    };

    action._id = actionId;

    this[methodName] = action;
  }

  cancelAction () {
    this.shouldDispatch = false;
  }
```

**Comment by bdowning** [comment]
But if we're moving from "returning a value dispatches" to "not cancelling an action dispatches" I'd think for consistency you'd want to be able to cancel an async action.  (Yes, this could get you in trouble since you'd get a Begin dispatch and not a Finished dispatch.  Caveat emptor.)

But really I just don't like typing extra stuff, the current bahavior makes sense to me, and having magic methods that modify behavior of currently-running-on-the-stack stuff through spooky action makes me feel uncomfortable.  Meh.

**Comment by jordansexton** [comment]
See above implementation. You can cancel an async action the same way.

**Comment by jordansexton** [comment]
The action method returns a promise, but the action method itself is not asynchronous, only the promise is. Therefore you can cancel the action synchronously even within an async action method.

**Comment by bdowning** [comment]
It doesn't fix my distaste of "having magic methods that modify behavior of currently-running-on-the-stack stuff through spooky action makes me feel uncomfortable".  Returning a value is clear, calling a method that flips a hidden variable isn't to me.

**Comment by jordansexton** [comment]
So what do you think is happening when you call `event.preventDefault()` in your click handler?

**Comment by bdowning** [comment]
I think `event` is actually an object specific to the currently-running event, not all events or all events of a certain class.  `this` in a action call is not specific to that action, so calling a method on it to cancel this specific action feels weird.

**Comment by bdowning** [comment]
(I think both approaches would work.  I just think the current one is clearer in my opinion, as well as resulting in less verbose code for the kind of Flux code I'm writing.)

**Comment by jordansexton** [comment]
Right, because actions are not canceling "themselves" anyway since they're just methods. They are telling the dispatcher not to dispatch them. To understand this requires some understanding of the context that actions run in.

We don't pass an "action" object into the handler (except for on async methods, where it's passed into the store) because we don't need to, but `event` has an API just like `this` has an API. Both are context dependent.

Currently, returning `undefined` requires you to implicitly understand that context. This is more explicit and the "magic" value stays an internal implementation detail of the library, not one that crosses over into application code.

However, I think there are some other open questions here. How often are people canceling actions? Is it a code smell to be canceling actions often? How often are people actually intending to cancel an action when they don't return a value?

To me this is about usability and least surprise, and the explicit option is less surprising and much more idiomatic in JavaScript. In most event and pub/sub libraries, returning no value from a handler means "proceed as normal", not "stop what you're doing".

**Comment by bdowning** [comment]
I think the current behavior makes it easier to make "meta-actions" composed of others but with no actual dispatch themselves; this allows similar patterns to other Flux frameworks' action creators with explicit dispatching.  See:

https://github.com/acdlite/flummox/issues/178#issuecomment-102069593

In general I've found lots of use for composed actions, so I'd hate to see them dismissed as a "code smell."  Since function composition is so basic to what (useful) programming is I'd hate to see action composition discouraged.

(Also in your sample implementation above you'll need to save off the current `this.shouldDispatch` into a local variable and restore it afterwards to not break on composed actions, otherwise the inner one will step on the state of the outer.)

**Comment by jordansexton** [comment]
No, I agree with you, I definitely use the type of composed actions you're describing all the time. But I just don't listen to them on my stores. If a store isn't listening to them, then the fact that they dispatch doesn't matter. I'm not describing returning `undefined` implicitly as a smell, but canceling an action's dispatch because of it. Actions should be relatively agnostic of stores; perhaps a store is interested in knowing when that composite action runs. This is why implicit non-dispatch is bad.

Your second point about the sample implementation makes sense. And to be fair, I'm not exactly in love with `this.shouldDispatch` not referring to the action method either. It's just that the current behavior is very magical (for JS), and setting a flag isn't.

There are some other slightly more internally complicated options here, like setting `this.shouldDispatch` on the wrapped action method itself by storing a reference to the one going on the stack.

**Comment by bdowning** [comment]
Fair enough.  I'm on the other side of the "what's magical" opinion but I recognize that it's an opinion.  I'd be interested in avoiding useless dispatch cycles in a large app with many stores, but I've never worked on such a beast so it's purely an academic desire for me.

**Comment by acdlite** [comment]
While I appreciate everyone's opinion on this, I'm going to close the issue. I like the existing behavior. If it's too "magical" for your taste, an alternative is to use `this.dispatch()` manually instead relying on the auto-dispatching of the return value.
