### ISSUE TITLE
strange behaviour in Actions

### ISSUE THREAD

**Issue by vesparny** [acdlite/flummox#20]
I have this Action

```js
'use strict';

var { Actions } = require('flummox');
var arrayUtils = require('../utils/arrayUtils');

class FavoritesActions extends Actions {

  addFavorite(id){
    var favorites = this.getAll();
    favorites.push(id);
    window.localStorage.setItem('favorites', JSON.stringify(favorites));
    return favorites;
  }

  removeFavorite(id){
    var favorites = this.getAll();
    arrayUtils.remove(favorites, id);
    window.localStorage.setItem('favorites', JSON.stringify(favorites));
    return favorites;
  }

  getAll(){
    return JSON.parse(window.localStorage.getItem('favorites')) || [];
  }
}

module.exports = FavoritesActions;
```

When I call the method `addFavorite()` internally I call the method `this.getAll()` and assign its result to `favorites`.
The problem is that `favorites.push(id)` seems to be executed before the method `this.getAll()` returns, like if it was async, and I get an error of course because favorites is undefined.

I don't know if the problem here is about something related to es6 which I'm a total noob at.

**Comment by acdlite** [comment]
@vesparny Which version of Flummox are you running? I believe this may have something to do with a bug that was fixed in version 2.3.

**Comment by acdlite** [comment]
@vesparny Oh, actually I see the problem now. All actions return undefined (or a promise that resolves to undefined) to their caller. This is by design, to enforce unidirectional data flow. Data fetching operations like `getAll()` should be in a separate class or module. Usually you'd call this something like WebAPIUtils. There's a section about this in the API docs for Actions: https://github.com/acdlite/flummox/blob/master/docs/api/Actions.md

**Comment by vesparny** [comment]
@acdlite yep it was just that. Thanks.
