### ISSUE TITLE
How to implement lazy preload of data

### ISSUE THREAD

**Issue by farnoy** [acdlite/flummox#207]
Hi,

I'm making a chat application and migrating to flummox right now. Pretty happy with all of it, but I do have one issue. I'm not sure what's the best way to do a conditional load of data.

Say you change channels in this chat application, and the app hasn't yet fetched the messages of the channel you're switching to. What's the best way to load this data?

My ideas:
- I was thinking about querying the store from the action,  so I can see if it has messages in that channel, or should I preload them. However, I don't like the bidirectional flow of data between Actions and Store in this example, I don't think it's how Flux should work.
- Checking the store from the view and dispatching an action to load missing data conditionally. Again, it's probably even worse than before because we have crucial data logic in the view.

Can you recommend a good way of solving this? Hope I explained clearly.

**Comment by bdowning** [comment]
I think it's debatable whether flux is about bidirectional flow of all data or just bidirectional flow of data mutations.  In particular, there's no real difference in data-flow terms between:

```javascript
/* Action */
async changeChannel(newChannel) {
    if (this.channelStore.needsUpdateFor(newChannel))
        await this.updateChannelFromServer(newChannel);
    return { newChannel };
}

/* Controller View */
this.channelActions.changeChannel(newChannel);
```

and

```javascript
/* Action */
async changeChannel(newChannel, needsUpdate) {
    if (needsUpdate)
        await this.updateChannelFromServer(newChannel);
    return { newChannel };
}

/* Controller View */
this.channelActions.changeChannel(
    newChannel,
    this.channelStore.needsUpdateFor(newChannel)
);
```

and

```javascript
/* Action */
changeChannel(newChannel) {
    return { newChannel };
}

/* Controller View */
if (this.channelStore.needsUpdateFor(newChannel))
    await this.channelActions.updateChannelFromServer(newChannel);
this.channelActions.changeChannel(newChannel);
```

Except that the second and third have more disconnected logic and require more code duplication if you need to change channels in multiple places.  Also the third does not delay the changeChannel[Finished] dispatch until the data is loaded, making it harder to prevent changing the UI until the data is present if that's what you want.  (In the first two cases you can still optimistically update the UI if you want by using the changeChannel[Begin] dispatch.)

I have turned into a big fan of composing bigger Actions out of smaller Actions, as seen in this example.  Especially with async Actions you can easily describe some pretty complicated async sequences that would otherwise need to be pieced together by complex logic shared between Actions, Stores, and controller Views, while still mostly preventing dispatch loops.

**Comment by farnoy** [comment]
Thanks for answering! I guess time will tell when my app evolves. I'll try to write back about my experience when my app grows.
