### ISSUE TITLE
Changes in 2 stores FluxComponent

### ISSUE THREAD

**Issue by tadjik1** [acdlite/flummox#220]
Hello.
My component relate on 2 stores: users and usersSearch.

```javascript
<FluxComponent
  q={query}
  connectToStores={['users', 'usersSearch']}
  stateGetter={([usersStore, usersSearchStore], props) => ({
    users: usersSearchStore.getUsersByQuery(props.q).map(id => usersStore.get(id)),
    isAlreadySearched: usersSearchStore.isAlreadySearched(props.q),
    isInProcess: usersSearchStore.isInProcess(props.q)
})}>
  <Users />
</FluxComponent>
```

When data arrives from server my stores changes:

usersStore keep information about all users (merge new)
usersSearchStore keep information about relations between search query and users list.

```javascript
//userStore.js
...
flux.addListener('dispatch', this.handleNewUsers.bind(this));
...

//usersSearchStore.js
...
this.registerAsync(usersActions.searchUsers,
  this.handleBeginSearch,
  this.handleSuccessSearch,
  this.handleFailedSearch
);
```

So my question is: how can I prevent fist changes and re-render my component only after full changes cycle? (both users store and users search store)

**Comment by johanneslumpe** [comment]
Right now there is no such thing, the component will pick up every single change in a store you are listening to.

@acdlite what do you think? This seems to be an edge-case, but maybe it could be possible for stores to use `setState` without emitting a change? That way a scenario like this could be covered. It wouldn't be perfect though, because maybe another component would want to listen to that store when it updates. Another idea would be to add some kind of dependency to `connect`, where we can specify that when store `A` updates, it shouldn't update itself, but only when store `B` updates. It does add additional complexity though.

**Comment by tadjik1** [comment]
@johanneslumpe unfortunately both of your ideas doesn't work correctly in this situation, the first one you've already explain and in the second scenario we will have the problem in case when only one store need to be updated. Maybe this problem with my architecture, but I don't know how to make it better.

**Comment by johanneslumpe** [comment]
@tadjik1 are you actually running into performance issues with those 2 renders? Or do you just don't want to render half of the data without the rest? Can you share the structure you are rendering?

**Comment by tadjik1** [comment]
I have no benchmarking and it's just a concept. I'm still afraid rerendering, maybe it's because I have a big backbone experience :)
I will share it today after some refactoring

**Comment by tadjik1** [comment]
@johanneslumpe this is my [experiments](https://github.com/tadjik1/soundcloud-player/tree/feature/local-api/src/scripts/shared/stores/Users). There no ideal code, I am still in researching.
