### ISSUE TITLE
Remove Actions class

### ISSUE THREAD

**Issue by acdlite** [acdlite/flummox#223]
Classes aren't the best way to model a group of actions, since actions are essentially just stateless functions. Using a plain object hash of functions is already supported, but internally it still relies on the Actions class. We should move the action wrapping logic into a separate module.

**Comment by bdowning** [comment]
What would be the model for the following then:

```javascript
export default class OrderEditorActions extends Actions {
    constructor(flux) {
        super();
        this.flux = flux;
    }

    async orderEditorStarted(orderId) {
        await this.flux.getActions('tix').fetchOrders({
            id: orderId
        });
        let order = this.flux.getStore('orders').getOrder(orderId);
        await this.flux.getActions('tix').fetchEvents({
            id: order.eventId
        });
        return { orderId };
    }

    ...
}
```

i.e. I need my Actions to have reference to flux (or possibly other data).  Would it move to being:

```javascript
export default class OrderEditorActions {
    constructor(flux) {
        this.flux = flux;
    }

    ...
}
```

and then rather than doing

```javascript
        this.createActions('order-editor', OrderEditorActions, this);
```

I would do:

```javascript
        this.createActions('order-editor', new OrderEditorActions(this));
```

?

I want to make sure this use-case is still easy to do, since sometimes actions do have state depending on which flux they're attached to.

**Comment by joaovpmamede** [comment]
@bdowning Wouldn't it be easy if you pass data to your actions instead of trying to get it from inside your actions?

**Comment by bdowning** [comment]
Possible?  Sure, I guess, it's still Turing complete after all.  Easy?  It'd certainly be more verbose and have less encapsulation.  Now all of my action call sites need to keep track of whatever random ancillary data the action may need, or whether it needs a flux pointer to fetch its own.  Taken to extremes, why have action creators at all and not just embed the action dispatch calls right inside the views?

If this were the flummox attitude I'd feel sort of like I'm being asked not to create closures because the values you'd close over could be passed into the function each time as arguments (and passed alongside the function whenever it's passed by value a la the ubiquitous `void *userdata` in C code).  Sure that's a valid argument but you're throwing away a lot of expressiveness.

The current way Actions are done IMHO provides useful levels of expressiveness in writing real code.  The claim made to support changing it is that "since actions are essentially just stateless functions", which I dispute.  I don't think you can make them just stateless functions without removing useful expressiveness that's being taken advantage of today.  I just want to make sure that whatever changes happen they don't reduce expressiveness or make it more verbose to accomplish the same thing.

**Comment by johanneslumpe** [comment]
Just to take away your worries: you can wrap the action object in a function and pass the flummox instance to it in the constructor, giving you access to it, without having to assign it to 'this' :) It's not more work and you still get the desired result.

**Comment by bdowning** [comment]
If that's the case my previously proposed solution:

```javascript
export default class OrderEditorActions {
    constructor(flux) {
        this.flux = flux;
    }

    ...
}
```

and

```javascript
        this.createActions('order-editor', new OrderEditorActions(this));
```

should also work, yes?

I'm not trying to make a value judgement of which is better than the other, but they should both work, correct?

**Comment by johanneslumpe** [comment]
@bdowning No that will not work. As the methods of your action are on the prototype and not properties of the object itself. So what you will end up with, is an object which has a `flux` property assigned, but no methods. The methods are extracted using `Object.keys`, which looks on the object, not the object's prototype.

**Comment by bdowning** [comment]
Yeah, I noticed the commits earlier today and read through it and came to the same conclusion.  I'm slightly annoyed by the syntactic differences now between class-based things (stores and components) and actions now, since actions are in a plain object (and needs commas between them) and everything else uses the class syntax (which is oddball and does not use commas); with the old Actions class everything was class based.  But I'll get over it.  And I'll admit that the class-based action wrapper code that was removed looked kinda gross.

Is there a roadmap/timescale for releasing 4.0?  I'm currently developing stuff and would like to use some of the 4.0 features (or at least not be writing soon-to-be-obsolete Flummox 3 code) but the API changes keep coming with little warning...

**Comment by johanneslumpe** [comment]
I think we actually merged all the breaking changes for 4.0. If you clone from master, you should have a version that you can use. But still: be careful, it's just the RC version.

**Comment by johanneslumpe** [comment]
And if you use my suggested way, you can still keep your classes ;)

**Comment by bdowning** [comment]
Oh, I started replying before I saw your edit.

Wow, that looks.... interesting.  The fact that I had to stare at it for a few minutes and read the expansion to convince myself that `method` would be bound to the right `this` certainly makes me pause...

**Comment by johanneslumpe** [comment]
@bdowning haha. I then there is no more confusion? If not, I'd like to close this, as the actual removal is already through.

**Comment by bdowning** [comment]
Feel free.

**Comment by johanneslumpe** [comment]
:+1:
